// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: main.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
*/
package main

import regexp "regexp"
import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_CreateRequest_Password = regexp.MustCompile("^[a-zA-Z0-9]{6,}$")

func (this *CreateRequest) Validate() error {
	if this.Username == "" {
		return go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must not be an empty string`, this.Username))
	}
	if !_regex_CreateRequest_Password.MatchString(this.Password) {
		return go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9]{6,}$"`, this.Password))
	}
	if !(this.Age > 0) {
		return go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be greater than '0'`, this.Age))
	}
	if !(this.Age < 120) {
		return go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be less than '120'`, this.Age))
	}
	return nil
}
func (this *CreateResponse) Validate() error {
	return nil
}
