// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Age      int64  `protobuf:"zigzag64,3,opt,name=age" json:"age,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateRequest) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type CreateResponse struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Age      int64  `protobuf:"zigzag64,4,opt,name=age" json:"age,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateResponse) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "main.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "main.CreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/main.User/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.User/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _User_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}

func init() { proto.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xd7, 0x3f, 0x94, 0xfa, 0x82, 0x63, 0x66, 0x82, 0xa5, 0x97, 0x8e, 0xe2, 0x61, 0x07,
	0xdb, 0x8a, 0xc3, 0x81, 0x07, 0x0f, 0xce, 0x6f, 0x50, 0x10, 0x44, 0x51, 0xc8, 0x6c, 0xa8, 0x51,
	0xdb, 0xd4, 0x24, 0xb5, 0xa2, 0x78, 0xf3, 0x7b, 0x16, 0xfa, 0x49, 0xa4, 0x09, 0x76, 0xdb, 0x2d,
	0x3c, 0x79, 0x5e, 0x7e, 0x3f, 0x1e, 0x80, 0x02, 0xd3, 0x32, 0xae, 0x38, 0x93, 0x0c, 0xd9, 0xfd,
	0xdb, 0x5f, 0xe6, 0x54, 0x3e, 0xd7, 0xeb, 0xf8, 0x89, 0x15, 0x49, 0xd1, 0x50, 0xf9, 0xca, 0x9a,
	0x24, 0x67, 0x91, 0xaa, 0x44, 0x1f, 0xf8, 0x8d, 0x66, 0x58, 0x32, 0x2e, 0x92, 0xe1, 0xa9, 0xaf,
	0xc3, 0x5f, 0x03, 0xf6, 0xaf, 0x39, 0xc1, 0x92, 0xa4, 0xe4, 0xbd, 0x26, 0x42, 0xa2, 0x10, 0xdc,
	0x5a, 0x10, 0x5e, 0xe2, 0x82, 0x78, 0xc6, 0xcc, 0x98, 0xef, 0xad, 0x9c, 0xae, 0x0d, 0xcc, 0x5b,
	0x23, 0x1d, 0x72, 0xb4, 0x00, 0xb7, 0xc2, 0x42, 0x34, 0x8c, 0x67, 0x9e, 0xa9, 0x3a, 0x47, 0x5d,
	0x1b, 0x4c, 0xe1, 0xe0, 0xf1, 0x1e, 0x47, 0x5f, 0x57, 0xd1, 0xdd, 0x69, 0x74, 0xf1, 0xf0, 0xbd,
	0x3c, 0xf9, 0x39, 0x4e, 0x87, 0x22, 0xf2, 0xc1, 0xc2, 0x39, 0xf1, 0xac, 0x99, 0x31, 0x47, 0x2b,
	0xb7, 0x6b, 0x03, 0x7b, 0x32, 0xf2, 0x3e, 0xd3, 0x3e, 0x0c, 0x5f, 0x60, 0xfc, 0x6f, 0x21, 0x2a,
	0x56, 0x0a, 0x82, 0xc6, 0x60, 0xd2, 0x4c, 0x09, 0xd8, 0xa9, 0x49, 0xfb, 0xeb, 0x8d, 0x96, 0x42,
	0x6e, 0xe9, 0xf8, 0x5b, 0x3a, 0x96, 0xfe, 0x1b, 0xa8, 0x13, 0x4d, 0xb5, 0x7b, 0xaa, 0x62, 0x9d,
	0x5d, 0x82, 0x7d, 0x23, 0x08, 0x47, 0xe7, 0xe0, 0x68, 0x26, 0x9a, 0xc6, 0x6a, 0xcf, 0x9d, 0x1d,
	0xfc, 0xc3, 0xdd, 0x50, 0x6b, 0x85, 0xa3, 0xb5, 0xa3, 0x86, 0x5b, 0xfc, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xd2, 0xc5, 0xa5, 0x53, 0x84, 0x01, 0x00, 0x00,
}
